### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by urshar** [jsanahuja/Notifier.js#1]
Is it possible to change the position of the notification? for example top-right

**Comment by jsanahuja** [comment]
It is not possible with a configuration but you can overwrite the CSS:
`.notifyjs-container {top: 0;right: 0.5em;}`
`.notifyjs-container .notifyjs-notification { margin-top: 0.5em; }`

Althought this won't change the notifications order, so the most recent won't be the one on the top. 

I will implement it

**Comment by jsanahuja** [comment]
Try the latest 1.2.0 release and the params `position` and `direction`. Note that I have made more changes than just these. See release notes and documentation

**Comment by urshar** [comment]
I have a problem. I set the position top-right and the notification is behind my page header.
I think the z-index is the problem. my header has default the z-index 1000; did you set a z-index?

**Comment by jsanahuja** [comment]
The default z-index is 100. I will increase it and add the option to change it

**Comment by jsanahuja** [comment]
Done, try with the 1.2.2 release
