### ISSUE TITLE
Notification type -> classes always empty

### ISSUE THREAD

**Issue by pedro-blablagues** [jsanahuja/Notifier.js#2]
Hello,
You script is really good! Many thanks for it!
I just find a strange thing: I try to customize the class of the notification using "classes" attribute like textColor, borderColor, etc ...
In my case, class of the notification is still empty and the configuration not working ...
Is it a bug?
It good be also great to add 2 functionnality:
- a callback when you click a noticiation,
- make the timer doing a break when the mouse is hover a notification

Many thanks!
Best regards,
Pierre

**Comment by jsanahuja** [comment]
> I just find a strange thing: I try to customize the class of the notification using "classes" attribute like textColor, borderColor, etc ...
> In my case, class of the notification is still empty and the configuration not working ...
> Is it a bug?

Yes it is. Fixed now in the latest release (1.2.4)

> It good be also great to add 2 functionnality:
> 
> * a callback when you click a noticiation,
> * make the timer doing a break when the mouse is hover a notification

I might implement it soon or if you want to can send a pull request

Thanks!

**Comment by pedro-blablagues** [comment]
Many thanks!
That's perfect!
Ok for the other points, I'll send pull request.
Best regards,
Pedro
