### ISSUE TITLE
Script not running in message

### ISSUE THREAD

**Issue by webwhizz** [jsanahuja/Notifier.js#3]
notifierTR.notify("error", "<script> </script>");

This will give you an idea of what I am trying to achieve. 

The notify should be able to run scripts e.g to redirect to another page when the alert pops up

**Comment by jsanahuja** [comment]
You can use the callback feature. This will be called right after the notification finishes.

Example:
```
var notifierTR = new Notifier();
notifierTR.notify("error", "There was an error. We will try again", 3000, function(){
    window.location.reload();
});
```

There is more info and examples in the docs: https://www.sowecms.com/demos/Notifier.js

**Comment by webwhizz** [comment]
Not exactly what I aim to achieve.

Trying to pass scripts as json results to notifier and it's not working.

Take for example

json_encode("<script> </script>");


Then with notifier, trying to output the result above won't run the script.

Bootstrap notify does that perfectly

**Comment by jsanahuja** [comment]
I just don't understand the purpose of that. Running code in the "global" scope? Can you please show a "real" use case?
